<<<<<<< HEAD
# .github/workflows/ci.yml
=======
>>>>>>> 676a004be1b787cad923b9789e91abb390df0d2b
name: CI

on:
  pull_request:
<<<<<<< HEAD
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]
=======
    branches: [main, dev]
  push:
    branches: [main, dev]
>>>>>>> 676a004be1b787cad923b9789e91abb390df0d2b

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'   # <-- important: Next.js requires >=20.9.0
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint || true

=======
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint || true
>>>>>>> 676a004be1b787cad923b9789e91abb390df0d2b
      - name: Build
        run: npm run build
